### ISSUE TITLE
Segmentation fault (core dumped) training Issue

### ISSUE THREAD

**Issue by kimseockho** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#12]
I want to get the result segmented to the vehicle in the final result, 
so I want to re-learn using erfnet_model_sim3d_7class.tar.

All dataset paths were checked, and the pytorch version and CUDA and cuDNN versions were matched.
But I only got the error below.
Segmentation fault (core dumped)

What is the problem?

If you had the same problem, please share a solution.

**Comment by Ivanyan0516** [comment]
I meet the same question, it bothers me a lot, have you solved it?

**Comment by tenngre** [comment]
You can use the old version from aliyun, such as version 6.XXX
