### ISSUE TITLE
使用IPM将mask转换为top-view的疑惑

### ISSUE THREAD

**Issue by mengpengfei** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#19]
你好，我看在训练GeoNet，首先使用了一个固定参数，将2D车道线mask，通过IPM方式转换为俯视图，请问这个固定的参数怎么来的，这个固定参数是否已经包含了相机外参（旋转矩阵和平移矩阵）。这个参数是否只是预先标定的，不太准确的外参。

**Comment by mengpengfei** [comment]
在车辆运动过程中相机的俯仰角patch 应该也是变化的，请问你这个固定的patch是怎么来的

**Comment by CharlesXu1124** [comment]
同问，如果相机内参改变应该怎么更改代码进行训练？相机外参的参照系是什么？

**Comment by yuliangguo** [comment]
@mengpengfei @CharlesXu1124 
这个虚拟数据集使用的是一个固定的相机外参，这里的定义一般是到车身坐标系，也有定义为接地点的坐标系的。在这个数据集上面训练的模型会是对camer参数overfit的，所以一般不能很好generalize到其他参数采集的图片中。如果想根据自己的情况重新训练，一般是需要重新运行类似的虚拟环境重新render图片和生成label的。当然大多数虚拟数据生成的code并不开源，很多是各自公司的重要知识产权。
