### ISSUE TITLE
Curvature computation

### ISSUE THREAD

**Issue by k-nayak** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#21]
I was just curious if the curvature that is computed in camera coordinate system is sufficient to use for the steering of the vehicle or is it recommended to compute the curvature in world coordinates as well. If yes, how can XYZ of a particular lane point be used to compute the curvature of the lane ? In traditional IPM based curvature detectection just the X and Y are used keeping Z=0 as it is on the road surface. Since camera to world transformation is rigid can i just rely on the curvature values in camera coordinate system ? 

Thanks in advance for any clarification or comments on my understanding. Please do let me know if i am missing something.

**Comment by yuliangguo** [comment]
Hello, thanks for the interesting question. Although I can not recall
exactly when I use curvature, I could try to answer your question.

For 3D curvature from a space curve, I found this page have a clear
instruction. 3.16 is the formula.

https://openstax.org/books/calculus-volume-3/pages/3-3-arc-length-and-curvature

And yes, you should just be OK to calculate it in camera coordinate system,
since it’s invariant to se3 transformation.

**Comment by k-nayak** [comment]
Thanks for the quick response. It is not exactly related to the 3D lane net. I just thought it would be a great place to ask questions regarding 3D points. 

Just to give a quick overview I am trying to use IPM for getting the curvature of the lane and using the Ultra fast structure-aware lane detection model for detecting the lane. And I was curious if the camera coordinate system is good enough for steering the vehicle or transforming to the world and computing is really required. As I never came across 3D coordinates and computing curvature for it. Since my tests are conducted in the Carla simulator the extrinsic can be easily obtained for transforming from camera to world. 

I appreciate your response for clearing up the concept, as i am also aware that camera to world is rigid transformation and the curvature values can be used for steering. Just looking for literature/expertise to verify my understanding.
