### ISSUE TITLE
A question about cost_mat in metric

### ISSUE THREAD

**Issue by Aguin** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#22]
Hi @yuliangguo ,
I think the implementation here https://github.com/yuliangguo/Pytorch_Generalized_3D_Lane_Detection/blob/master/tools/eval_3D_lane.py#L165 is not exactly consistent with the formula in the paper.
![2022-07-04 12-50-53 的屏幕截图](https://user-images.githubusercontent.com/16891787/177083664-e7edc892-b814-4fc4-97f5-c910a13bf96f.png)
Besides, I also want to know why not use num_match_mat or something like match_ratio as the cost_mat.

**Comment by yuliangguo** [comment]
> Hey, thanks for the questions. I am trying hard to recall the details. Hopefully the following answers your questions.

1. I think you are right, there might be a typo in the paper. The middle case might not exist. The reported result should respect the code.
2. There are some technical issues via using this MinCostFlow tool. First, it seems to only accept integer types. Second, the optimizer sometimes fails when using num_match_mat. 

Ideally, the best solver should be the BSDS's bipartite matching for boundary matching, https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/bsds/. However, it is old code implemented in matlab. I chose to implement MinCostFlow as a modern alternative way in python, but it has some limitations in the flexibility.

**Comment by yuliangguo** [comment]
Hey there, thanks for the questions. I am trying hard to recall the
details. Hopefully the following answers your questions.

1. I think you are right, there might be a typo in the paper. The middle
case might not exist. The reported result should respect the code.
2. There are some technical issues via using this MinCostFlow tool. First,
it seems to only accept integer types. Second, the optimizer sometimes
fails when using num_match_mat.

Ideally, the best solver should be the BSDS's bipartite matching for
boundary matching,
https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/bsds/. However,
it is old code implemented in matlab. I chose to implement MinCostFlow as a
modern alternative way in python, but it has some limitations in the
flexibility.
