### ISSUE TITLE
A question about estimate z for 3D lane

### ISSUE THREAD

**Issue by Monkey-Hu** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#4]
Thanks for your amazing work. 
I have read Part 3.1 and I just cannot understand the  process of estimating z for 3D lane. After the first and second trasformation，I think there should only be red curves on the following image. So where do these blue curves come from? Thank you very much for answering my questions .
![1596187663(1)](https://user-images.githubusercontent.com/32889493/89021463-2a153280-d353-11ea-99a6-322ce8312e5a.png)

**Comment by maxenceliu** [comment]
both red and blue lines are ground truth, which use different projection method. reds are IPM projection. blues are (x,y,z）-->(x,y,0)

**Comment by Monkey-Hu** [comment]
> both red and blue lines are ground truth, which use different projection method. reds are IPM projection. blues are (x,y,z）-->(x,y,0)

that makes sense. thanks for help~

**Comment by yuliangguo** [comment]
@Monkey-Hu Thank you for the question. @maxenceliu Thank you for the correct answer.

**Comment by voldemortX** [comment]
@yuliangguo I've read your paper and @maxenceliu's explanations, but I still can't fully understand this. If reds are got from IPM, shouldn't lanes be parallel already? Why do we need to move them to be parallel? My main question is: how is it possible to ascertain heights with 2D segmentation map on the captured image as input? Could you guys elaborate a little so I could understand this better.
