### ISSUE TITLE
Pretrained ERFNet has not been trained with real world data.

### ISSUE THREAD

**Issue by maxenceliu** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#5]

**Comment by yuliangguo** [comment]
You are right. In our code, we only provide the experiments limited to the systhetic dataset. If to consider real-world application, a lot additional work both on methods and dataset needs to be done. I would suggest 1. training segmentation network on huge 2D real world dataset. 2. More synthetic binary maps associated with 3D lanelines considering highly diversed terrian maps.
