### ISSUE TITLE
about pred_hcam and pred_pitch

### ISSUE THREAD

**Issue by pandiii** [yuliangguo/Pytorch_Generalized_3D_Lane_Detection#8]
Thank you very much for your code, I'm an employee of the national intelligent vehicle innovation center. 
In LaneNet3D.py, pred_hcam and pred_pitch are obtained by training, but in GeoNet3D.py I found that they're both directly assigned without training.
I want to know why assign them directly without training? Maybe I misunderstood, Hope to get your reply ~~
Thank you again for your code!

**Comment by yuliangguo** [comment]
Thanks for asking. Fixing camera height and angle is indeed a
simplified setup such that the design can focus on improving the 3D lanes.
In the real scenario, fixing the height may not affect much, but the camera
pitch and yaw angle should be estimated online.  There are third-party
online calibration networks or classic methods to be considered to
integrate into this approach.

**Comment by pandiii** [comment]
Thank you for your quick reply! 
We are doing comparative experiments, including 3D-LaneNet(GM), Gen-LaneNet(Apollo) and GM's latest paper(3D-LaneNet++). Unified use your open source Apollo Synthetic Dataset. And the experimental results you provide as a reference.
But I found that GM's hcam and pitch are predicted by a network, yours are as known variables. This results in the unfairness of the experiment. Is this comparison convincing? 
Maybe I missed some details, hope to get your explanation ~~

**Comment by yuliangguo** [comment]
Not a problem. In my experiments, I did not use the pose predictor, and
give their method fixed values too, so the comparison only focuses on
lanes. Unfortunately I did not implement their pose estimator in my repo
due to time limit. You may need some extra work to integrate it for both
pipelines from my version.

**Comment by pandiii** [comment]
I see. It's consistent if you also give them fixed values.
Your code greatly shortens our development and experiment time, as well as the result baseline that you set up.
Thanks again!

**Comment by ElvishElvis** [comment]
@pandiii hello, I am recently conducting the same experiements under similar setting, could we have a closer conversation about this topic under your convenience? Thanks, my email is elvishelvis6@gmail.com
